name = "charging-stations-bot"
compatibility_date = "2026-03-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "charging-stations-db"
database_id = "a34e22d7-527e-4bbe-88e0-b1cfc9a8f33b"
