/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient/index'
import { Route as DoctorIndexRouteImport } from './routes/doctor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PatientProfileRouteImport } from './routes/patient/profile'
import { Route as PatientOrdersRouteImport } from './routes/patient/orders'
import { Route as DoctorProfileRouteImport } from './routes/doctor/profile'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as DoctorOrdersIndexRouteImport } from './routes/doctor/orders/index'
import { Route as AdminServicesIndexRouteImport } from './routes/admin/services/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminDoctorsIndexRouteImport } from './routes/admin/doctors/index'
import { Route as DoctorOrdersOrderIdRouteImport } from './routes/doctor/orders/$orderId'
import { Route as AdminServicesNewRouteImport } from './routes/admin/services/new'
import { Route as AdminServicesServiceIdRouteImport } from './routes/admin/services/$serviceId'
import { Route as AdminOrdersNewRouteImport } from './routes/admin/orders/new'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders/$orderId'
import { Route as AdminDoctorsNewRouteImport } from './routes/admin/doctors/new'
import { Route as AdminDoctorsDoctorIdRouteImport } from './routes/admin/doctors/$doctorId'

const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientOrdersRoute = PatientOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const DoctorOrdersIndexRoute = DoctorOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsIndexRoute = AdminDoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => AdminRoute,
} as any)
const DoctorOrdersOrderIdRoute = DoctorOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminServicesNewRoute = AdminServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesServiceIdRoute = AdminServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersNewRoute = AdminOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsNewRoute = AdminDoctorsNewRouteImport.update({
  id: '/doctors/new',
  path: '/doctors/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsDoctorIdRoute = AdminDoctorsDoctorIdRouteImport.update({
  id: '/doctors/$doctorId',
  path: '/doctors/$doctorId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/patient/orders': typeof PatientOrdersRoute
  '/patient/profile': typeof PatientProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/admin/doctors/$doctorId': typeof AdminDoctorsDoctorIdRoute
  '/admin/doctors/new': typeof AdminDoctorsNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/services/$serviceId': typeof AdminServicesServiceIdRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/doctor/orders/$orderId': typeof DoctorOrdersOrderIdRoute
  '/admin/doctors/': typeof AdminDoctorsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/doctor/orders/': typeof DoctorOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/patient/orders': typeof PatientOrdersRoute
  '/patient/profile': typeof PatientProfileRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
  '/admin/doctors/$doctorId': typeof AdminDoctorsDoctorIdRoute
  '/admin/doctors/new': typeof AdminDoctorsNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/services/$serviceId': typeof AdminServicesServiceIdRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/doctor/orders/$orderId': typeof DoctorOrdersOrderIdRoute
  '/admin/doctors': typeof AdminDoctorsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/doctor/orders': typeof DoctorOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/patient/orders': typeof PatientOrdersRoute
  '/patient/profile': typeof PatientProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/admin/doctors/$doctorId': typeof AdminDoctorsDoctorIdRoute
  '/admin/doctors/new': typeof AdminDoctorsNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/services/$serviceId': typeof AdminServicesServiceIdRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/doctor/orders/$orderId': typeof DoctorOrdersOrderIdRoute
  '/admin/doctors/': typeof AdminDoctorsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/doctor/orders/': typeof DoctorOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/login'
    | '/patient'
    | '/admin/profile'
    | '/doctor/profile'
    | '/patient/orders'
    | '/patient/profile'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/admin/doctors/$doctorId'
    | '/admin/doctors/new'
    | '/admin/orders/$orderId'
    | '/admin/orders/new'
    | '/admin/services/$serviceId'
    | '/admin/services/new'
    | '/doctor/orders/$orderId'
    | '/admin/doctors/'
    | '/admin/orders/'
    | '/admin/services/'
    | '/doctor/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/profile'
    | '/doctor/profile'
    | '/patient/orders'
    | '/patient/profile'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/admin/doctors/$doctorId'
    | '/admin/doctors/new'
    | '/admin/orders/$orderId'
    | '/admin/orders/new'
    | '/admin/services/$serviceId'
    | '/admin/services/new'
    | '/doctor/orders/$orderId'
    | '/admin/doctors'
    | '/admin/orders'
    | '/admin/services'
    | '/doctor/orders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/login'
    | '/patient'
    | '/admin/profile'
    | '/doctor/profile'
    | '/patient/orders'
    | '/patient/profile'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/admin/doctors/$doctorId'
    | '/admin/doctors/new'
    | '/admin/orders/$orderId'
    | '/admin/orders/new'
    | '/admin/services/$serviceId'
    | '/admin/services/new'
    | '/doctor/orders/$orderId'
    | '/admin/doctors/'
    | '/admin/orders/'
    | '/admin/services/'
    | '/doctor/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/orders': {
      id: '/patient/orders'
      path: '/orders'
      fullPath: '/patient/orders'
      preLoaderRoute: typeof PatientOrdersRouteImport
      parentRoute: typeof PatientRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/doctor/orders/': {
      id: '/doctor/orders/'
      path: '/orders'
      fullPath: '/doctor/orders/'
      preLoaderRoute: typeof DoctorOrdersIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors/': {
      id: '/admin/doctors/'
      path: '/doctors'
      fullPath: '/admin/doctors/'
      preLoaderRoute: typeof AdminDoctorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/doctor/orders/$orderId': {
      id: '/doctor/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/doctor/orders/$orderId'
      preLoaderRoute: typeof DoctorOrdersOrderIdRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/services/new': {
      id: '/admin/services/new'
      path: '/services/new'
      fullPath: '/admin/services/new'
      preLoaderRoute: typeof AdminServicesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services/$serviceId': {
      id: '/admin/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/admin/services/$serviceId'
      preLoaderRoute: typeof AdminServicesServiceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/new': {
      id: '/admin/orders/new'
      path: '/orders/new'
      fullPath: '/admin/orders/new'
      preLoaderRoute: typeof AdminOrdersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors/new': {
      id: '/admin/doctors/new'
      path: '/doctors/new'
      fullPath: '/admin/doctors/new'
      preLoaderRoute: typeof AdminDoctorsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors/$doctorId': {
      id: '/admin/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/admin/doctors/$doctorId'
      preLoaderRoute: typeof AdminDoctorsDoctorIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminProfileRoute: typeof AdminProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDoctorsDoctorIdRoute: typeof AdminDoctorsDoctorIdRoute
  AdminDoctorsNewRoute: typeof AdminDoctorsNewRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminOrdersNewRoute: typeof AdminOrdersNewRoute
  AdminServicesServiceIdRoute: typeof AdminServicesServiceIdRoute
  AdminServicesNewRoute: typeof AdminServicesNewRoute
  AdminDoctorsIndexRoute: typeof AdminDoctorsIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProfileRoute: AdminProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDoctorsDoctorIdRoute: AdminDoctorsDoctorIdRoute,
  AdminDoctorsNewRoute: AdminDoctorsNewRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminOrdersNewRoute: AdminOrdersNewRoute,
  AdminServicesServiceIdRoute: AdminServicesServiceIdRoute,
  AdminServicesNewRoute: AdminServicesNewRoute,
  AdminDoctorsIndexRoute: AdminDoctorsIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorRouteChildren {
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorOrdersOrderIdRoute: typeof DoctorOrdersOrderIdRoute
  DoctorOrdersIndexRoute: typeof DoctorOrdersIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorOrdersOrderIdRoute: DoctorOrdersOrderIdRoute,
  DoctorOrdersIndexRoute: DoctorOrdersIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PatientRouteChildren {
  PatientOrdersRoute: typeof PatientOrdersRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientOrdersRoute: PatientOrdersRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
